/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.accdesign;

import java.awt.CardLayout;
import java.text.DateFormat;
import java.util.Date;


/**
 *
 * @author leong
 */
public class Basic extends javax.swing.JFrame {

    /**
     * Creates new form Basic
     */
    public Basic() {
        initComponents();

    }

    
//    public void clock() { 
//        Timer t = new Timer(0, new ActionListener() {
//                @Override
//                public void actionPerformed(ActionEvent e) { 
//                    
//                    Date date = new Date();
//                    SimpleDataFormat st = new SimpleDateFormat("hh:mm:ss");
//                    
//                    String tt = st.format(dt);
//                }
//                        
//        });
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        holderPane = new javax.swing.JPanel();
        homePane = new javax.swing.JPanel();
        baseDisplay = new javax.swing.JLayeredPane();
        jTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        toGoBut = new javax.swing.JButton();
        addTabBut = new javax.swing.JButton();
        bookingBut = new javax.swing.JButton();
        adminBut = new javax.swing.JButton();
        clockIOBut = new javax.swing.JButton();
        payBillBut = new javax.swing.JButton();
        menuBut = new javax.swing.JButton();
        addOrderPane = new javax.swing.JPanel();
        orderSplit = new javax.swing.JSplitPane();
        recPanel = new javax.swing.JLayeredPane();
        recAdds = new javax.swing.JScrollPane();
        recTabInfoTxt = new javax.swing.JPanel();
        RecOrdNum = new javax.swing.JLabel();
        RecTableNum = new javax.swing.JLabel();
        RecName = new javax.swing.JLabel();
        recInfoTxt = new javax.swing.JPanel();
        nameTxt = new javax.swing.JLabel();
        qtyTxt = new javax.swing.JLabel();
        eachTxt = new javax.swing.JLabel();
        eachTxt1 = new javax.swing.JLabel();
        viewMenuPanel = new javax.swing.JLayeredPane();
        foodBut = new javax.swing.JButton();
        dessBut = new javax.swing.JButton();
        drinksBut = new javax.swing.JButton();
        miscBut = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        displayMenu = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bookingPane = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        tab3 = new javax.swing.JButton();
        tab2 = new javax.swing.JButton();
        tab1 = new javax.swing.JButton();
        tab4 = new javax.swing.JButton();
        tab8 = new javax.swing.JButton();
        tab9 = new javax.swing.JButton();
        tab5 = new javax.swing.JButton();
        tab6 = new javax.swing.JButton();
        tab10 = new javax.swing.JButton();
        tab11 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        payBill = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        toGo = new javax.swing.JPanel();
        orderSplit1 = new javax.swing.JSplitPane();
        recPanel1 = new javax.swing.JLayeredPane();
        recAdds1 = new javax.swing.JScrollPane();
        recTabInfoTxt1 = new javax.swing.JPanel();
        RecOrdNum1 = new javax.swing.JLabel();
        RecTableNum1 = new javax.swing.JLabel();
        RecName1 = new javax.swing.JLabel();
        recInfoTxt1 = new javax.swing.JPanel();
        nameTxt1 = new javax.swing.JLabel();
        qtyTxt1 = new javax.swing.JLabel();
        eachTxt2 = new javax.swing.JLabel();
        eachTxt3 = new javax.swing.JLabel();
        viewMenuPanel1 = new javax.swing.JLayeredPane();
        foodBut1 = new javax.swing.JButton();
        dessBut1 = new javax.swing.JButton();
        drinksBut1 = new javax.swing.JButton();
        miscBut1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        displayMenu1 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("U&ME RESTAURAUNT POS");
        setBackground(new java.awt.Color(3, 20, 36));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 675));

        holderPane.setPreferredSize(new java.awt.Dimension(1200, 675));
        holderPane.setLayout(new java.awt.CardLayout());

        homePane.setBackground(new java.awt.Color(153, 161, 172));
        homePane.setPreferredSize(new java.awt.Dimension(1200, 675));

        baseDisplay.setBackground(new java.awt.Color(29, 39, 49));
        baseDisplay.setOpaque(true);
        baseDisplay.setPreferredSize(new java.awt.Dimension(696, 675));

        jTime.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jTime.setForeground(new java.awt.Color(255, 255, 255));
        jTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jTime.setText(DateFormat.getTimeInstance(DateFormat.SHORT).format(new Date()));
        jTime.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(DateFormat.getDateInstance(DateFormat.SHORT).format(new Date()));
        jLabel1.setToolTipText("");

        baseDisplay.setLayer(jTime, javax.swing.JLayeredPane.DEFAULT_LAYER);
        baseDisplay.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout baseDisplayLayout = new javax.swing.GroupLayout(baseDisplay);
        baseDisplay.setLayout(baseDisplayLayout);
        baseDisplayLayout.setHorizontalGroup(
            baseDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseDisplayLayout.createSequentialGroup()
                .addContainerGap(360, Short.MAX_VALUE)
                .addGroup(baseDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTime, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(39, 39, 39))
        );
        baseDisplayLayout.setVerticalGroup(
            baseDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseDisplayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        toGoBut.setBackground(new java.awt.Color(73, 100, 146));
        toGoBut.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        toGoBut.setForeground(new java.awt.Color(255, 255, 255));
        toGoBut.setText("TO GO");
        toGoBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 68, 102), 5));
        toGoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toGoButActionPerformed(evt);
            }
        });

        addTabBut.setBackground(new java.awt.Color(73, 100, 146));
        addTabBut.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        addTabBut.setForeground(new java.awt.Color(255, 255, 255));
        addTabBut.setText("ORDER");
        addTabBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 68, 102), 5));
        addTabBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTabButActionPerformed(evt);
            }
        });

        bookingBut.setBackground(new java.awt.Color(73, 100, 146));
        bookingBut.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bookingBut.setForeground(new java.awt.Color(255, 255, 255));
        bookingBut.setText("BOOKING");
        bookingBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 68, 102), 5));
        bookingBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingButActionPerformed(evt);
            }
        });

        adminBut.setBackground(new java.awt.Color(73, 100, 146));
        adminBut.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        adminBut.setForeground(new java.awt.Color(255, 255, 255));
        adminBut.setText("ADMIN");
        adminBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 68, 102), 5));
        adminBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButActionPerformed(evt);
            }
        });

        clockIOBut.setBackground(new java.awt.Color(73, 100, 146));
        clockIOBut.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        clockIOBut.setForeground(new java.awt.Color(255, 255, 255));
        clockIOBut.setText("CLOCK I/O");
        clockIOBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 68, 102), 5));

        payBillBut.setBackground(new java.awt.Color(73, 100, 146));
        payBillBut.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        payBillBut.setForeground(new java.awt.Color(255, 255, 255));
        payBillBut.setText("PAY BILL");
        payBillBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 68, 102), 5));

        menuBut.setBackground(new java.awt.Color(73, 100, 146));
        menuBut.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        menuBut.setForeground(new java.awt.Color(255, 255, 255));
        menuBut.setText("MENU");
        menuBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 68, 102), 5));
        menuBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePaneLayout = new javax.swing.GroupLayout(homePane);
        homePane.setLayout(homePaneLayout);
        homePaneLayout.setHorizontalGroup(
            homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePaneLayout.createSequentialGroup()
                .addComponent(baseDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminBut, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homePaneLayout.createSequentialGroup()
                        .addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(payBillBut, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clockIOBut, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(menuBut, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(bookingBut, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addTabBut, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toGoBut, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );
        homePaneLayout.setVerticalGroup(
            homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toGoBut, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuBut, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addTabBut, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payBillBut, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingBut, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clockIOBut, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(adminBut, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addComponent(baseDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        holderPane.add(homePane, "homePane");

        addOrderPane.setBackground(new java.awt.Color(29, 39, 49));
        addOrderPane.setPreferredSize(new java.awt.Dimension(1200, 675));

        orderSplit.setBackground(new java.awt.Color(68, 91, 115));
        orderSplit.setDividerLocation(550);
        orderSplit.setDividerSize(0);
        orderSplit.setPreferredSize(new java.awt.Dimension(1200, 630));

        recPanel.setBackground(new java.awt.Color(204, 204, 204));
        recPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 91, 115), 10));
        recPanel.setOpaque(true);
        recPanel.setPreferredSize(new java.awt.Dimension(550, 630));

        recTabInfoTxt.setBackground(new java.awt.Color(204, 204, 204));

        RecOrdNum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RecOrdNum.setText("#XXX");

        RecTableNum.setText("Table #");

        RecName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RecName.setText("SURNAME LASTNAME");

        javax.swing.GroupLayout recTabInfoTxtLayout = new javax.swing.GroupLayout(recTabInfoTxt);
        recTabInfoTxt.setLayout(recTabInfoTxtLayout);
        recTabInfoTxtLayout.setHorizontalGroup(
            recTabInfoTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recTabInfoTxtLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(RecOrdNum)
                .addGap(18, 18, 18)
                .addComponent(RecTableNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RecName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        recTabInfoTxtLayout.setVerticalGroup(
            recTabInfoTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recTabInfoTxtLayout.createSequentialGroup()
                .addGroup(recTabInfoTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecOrdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecTableNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nameTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(91, 138, 150));
        nameTxt.setText("Name");

        qtyTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        qtyTxt.setForeground(new java.awt.Color(91, 138, 150));
        qtyTxt.setText("QTY");

        eachTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eachTxt.setForeground(new java.awt.Color(91, 138, 150));
        eachTxt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eachTxt.setText("Each");

        eachTxt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eachTxt1.setForeground(new java.awt.Color(91, 138, 150));
        eachTxt1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eachTxt1.setText("Total $$$");

        javax.swing.GroupLayout recInfoTxtLayout = new javax.swing.GroupLayout(recInfoTxt);
        recInfoTxt.setLayout(recInfoTxtLayout);
        recInfoTxtLayout.setHorizontalGroup(
            recInfoTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recInfoTxtLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(nameTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(qtyTxt)
                .addGap(35, 35, 35)
                .addComponent(eachTxt)
                .addGap(35, 35, 35)
                .addComponent(eachTxt1)
                .addGap(9, 9, 9))
        );
        recInfoTxtLayout.setVerticalGroup(
            recInfoTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recInfoTxtLayout.createSequentialGroup()
                .addGroup(recInfoTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eachTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eachTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        recPanel.setLayer(recAdds, javax.swing.JLayeredPane.DEFAULT_LAYER);
        recPanel.setLayer(recTabInfoTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        recPanel.setLayer(recInfoTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout recPanelLayout = new javax.swing.GroupLayout(recPanel);
        recPanel.setLayout(recPanelLayout);
        recPanelLayout.setHorizontalGroup(
            recPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recTabInfoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(recAdds)
            .addComponent(recInfoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        recPanelLayout.setVerticalGroup(
            recPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recPanelLayout.createSequentialGroup()
                .addComponent(recTabInfoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(recInfoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(recAdds, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        orderSplit.setLeftComponent(recPanel);

        viewMenuPanel.setBackground(new java.awt.Color(204, 204, 204));
        viewMenuPanel.setOpaque(true);

        foodBut.setText("FOOD");
        foodBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodButActionPerformed(evt);
            }
        });

        dessBut.setText("DESSERT");

        drinksBut.setText("DRINKS");

        miscBut.setText("MISC.");

        jSeparator2.setForeground(new java.awt.Color(68, 91, 115));
        jSeparator2.setToolTipText("");
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        displayMenu.setLayout(new java.awt.CardLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 91, 115), 3));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        displayMenu.add(jScrollPane1, "card2");

        viewMenuPanel.setLayer(foodBut, javax.swing.JLayeredPane.DEFAULT_LAYER);
        viewMenuPanel.setLayer(dessBut, javax.swing.JLayeredPane.DEFAULT_LAYER);
        viewMenuPanel.setLayer(drinksBut, javax.swing.JLayeredPane.DEFAULT_LAYER);
        viewMenuPanel.setLayer(miscBut, javax.swing.JLayeredPane.DEFAULT_LAYER);
        viewMenuPanel.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        viewMenuPanel.setLayer(displayMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout viewMenuPanelLayout = new javax.swing.GroupLayout(viewMenuPanel);
        viewMenuPanel.setLayout(viewMenuPanelLayout);
        viewMenuPanelLayout.setHorizontalGroup(
            viewMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMenuPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(viewMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayMenu)
                    .addGroup(viewMenuPanelLayout.createSequentialGroup()
                        .addComponent(foodBut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(dessBut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(drinksBut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(miscBut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        viewMenuPanelLayout.setVerticalGroup(
            viewMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMenuPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(viewMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodBut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dessBut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinksBut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miscBut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        orderSplit.setRightComponent(viewMenuPanel);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ORDER #XXX");

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 0));
        jButton1.setText("BACK");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 0));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addOrderPaneLayout = new javax.swing.GroupLayout(addOrderPane);
        addOrderPane.setLayout(addOrderPaneLayout);
        addOrderPaneLayout.setHorizontalGroup(
            addOrderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderSplit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addOrderPaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        addOrderPaneLayout.setVerticalGroup(
            addOrderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addOrderPaneLayout.createSequentialGroup()
                .addGroup(addOrderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addOrderPaneLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(orderSplit, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        holderPane.add(addOrderPane, "addOrdPane");

        tab3.setText("3");
        jLayeredPane1.add(tab3);
        tab3.setBounds(240, 3, 80, 110);

        tab2.setText("2");
        tab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(tab2);
        tab2.setBounds(130, 3, 80, 110);

        tab1.setText("1");
        tab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(tab1);
        tab1.setBounds(25, 3, 80, 110);

        tab4.setText("4");
        jLayeredPane1.add(tab4);
        tab4.setBounds(351, 3, 80, 110);

        tab8.setText("8");
        jLayeredPane1.add(tab8);
        tab8.setBounds(950, 3, 80, 110);

        tab9.setText("9");
        jLayeredPane1.add(tab9);
        tab9.setBounds(1071, 3, 80, 110);

        tab5.setText("5");
        jLayeredPane1.add(tab5);
        tab5.setBounds(460, 20, 60, 80);

        tab6.setText("6");
        jLayeredPane1.add(tab6);
        tab6.setBounds(461, 113, 60, 80);

        tab10.setText("10");
        jLayeredPane1.add(tab10);
        tab10.setBounds(351, 363, 80, 110);

        tab11.setText("11");
        jLayeredPane1.add(tab11);
        tab11.setBounds(180, 543, 110, 70);

        jButton17.setText("7");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton17);
        jButton17.setBounds(620, 230, 70, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/accdesign/Drawing-55.sketchpad.png"))); // NOI18N
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1200, 680);

        javax.swing.GroupLayout bookingPaneLayout = new javax.swing.GroupLayout(bookingPane);
        bookingPane.setLayout(bookingPaneLayout);
        bookingPaneLayout.setHorizontalGroup(
            bookingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        bookingPaneLayout.setVerticalGroup(
            bookingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        holderPane.add(bookingPane, "card4");

        jLabel5.setText("jLabel5");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout payBillLayout = new javax.swing.GroupLayout(payBill);
        payBill.setLayout(payBillLayout);
        payBillLayout.setHorizontalGroup(
            payBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payBillLayout.createSequentialGroup()
                .addGroup(payBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payBillLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(payBillLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        payBillLayout.setVerticalGroup(
            payBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payBillLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        holderPane.add(payBill, "card5");

        toGo.setBackground(new java.awt.Color(29, 39, 49));
        toGo.setPreferredSize(new java.awt.Dimension(1200, 675));

        orderSplit1.setBackground(new java.awt.Color(68, 91, 115));
        orderSplit1.setDividerLocation(550);
        orderSplit1.setDividerSize(0);
        orderSplit1.setPreferredSize(new java.awt.Dimension(1200, 630));

        recPanel1.setBackground(new java.awt.Color(204, 204, 204));
        recPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 91, 115), 10));
        recPanel1.setOpaque(true);
        recPanel1.setPreferredSize(new java.awt.Dimension(550, 630));

        recTabInfoTxt1.setBackground(new java.awt.Color(204, 204, 204));

        RecOrdNum1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RecOrdNum1.setText("#XXX");

        RecTableNum1.setText("Table #");

        RecName1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RecName1.setText("SURNAME LASTNAME");

        javax.swing.GroupLayout recTabInfoTxt1Layout = new javax.swing.GroupLayout(recTabInfoTxt1);
        recTabInfoTxt1.setLayout(recTabInfoTxt1Layout);
        recTabInfoTxt1Layout.setHorizontalGroup(
            recTabInfoTxt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recTabInfoTxt1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(RecOrdNum1)
                .addGap(18, 18, 18)
                .addComponent(RecTableNum1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RecName1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        recTabInfoTxt1Layout.setVerticalGroup(
            recTabInfoTxt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recTabInfoTxt1Layout.createSequentialGroup()
                .addGroup(recTabInfoTxt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecOrdNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecTableNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecName1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nameTxt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameTxt1.setForeground(new java.awt.Color(91, 138, 150));
        nameTxt1.setText("Name");

        qtyTxt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        qtyTxt1.setForeground(new java.awt.Color(91, 138, 150));
        qtyTxt1.setText("QTY");

        eachTxt2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eachTxt2.setForeground(new java.awt.Color(91, 138, 150));
        eachTxt2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eachTxt2.setText("Each");

        eachTxt3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eachTxt3.setForeground(new java.awt.Color(91, 138, 150));
        eachTxt3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eachTxt3.setText("Total $$$");

        javax.swing.GroupLayout recInfoTxt1Layout = new javax.swing.GroupLayout(recInfoTxt1);
        recInfoTxt1.setLayout(recInfoTxt1Layout);
        recInfoTxt1Layout.setHorizontalGroup(
            recInfoTxt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recInfoTxt1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(nameTxt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(qtyTxt1)
                .addGap(35, 35, 35)
                .addComponent(eachTxt2)
                .addGap(35, 35, 35)
                .addComponent(eachTxt3)
                .addGap(9, 9, 9))
        );
        recInfoTxt1Layout.setVerticalGroup(
            recInfoTxt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recInfoTxt1Layout.createSequentialGroup()
                .addGroup(recInfoTxt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eachTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eachTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        recPanel1.setLayer(recAdds1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        recPanel1.setLayer(recTabInfoTxt1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        recPanel1.setLayer(recInfoTxt1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout recPanel1Layout = new javax.swing.GroupLayout(recPanel1);
        recPanel1.setLayout(recPanel1Layout);
        recPanel1Layout.setHorizontalGroup(
            recPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recTabInfoTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(recAdds1)
            .addComponent(recInfoTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        recPanel1Layout.setVerticalGroup(
            recPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recPanel1Layout.createSequentialGroup()
                .addComponent(recTabInfoTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(recInfoTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(recAdds1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        orderSplit1.setLeftComponent(recPanel1);

        viewMenuPanel1.setBackground(new java.awt.Color(204, 204, 204));
        viewMenuPanel1.setOpaque(true);

        foodBut1.setText("FOOD");
        foodBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodBut1ActionPerformed(evt);
            }
        });

        dessBut1.setText("DESSERT");

        drinksBut1.setText("DRINKS");

        miscBut1.setText("MISC.");

        jSeparator3.setForeground(new java.awt.Color(68, 91, 115));
        jSeparator3.setToolTipText("");
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        displayMenu1.setLayout(new java.awt.CardLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 91, 115), 3));
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        displayMenu1.add(jScrollPane2, "card2");

        viewMenuPanel1.setLayer(foodBut1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        viewMenuPanel1.setLayer(dessBut1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        viewMenuPanel1.setLayer(drinksBut1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        viewMenuPanel1.setLayer(miscBut1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        viewMenuPanel1.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        viewMenuPanel1.setLayer(displayMenu1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout viewMenuPanel1Layout = new javax.swing.GroupLayout(viewMenuPanel1);
        viewMenuPanel1.setLayout(viewMenuPanel1Layout);
        viewMenuPanel1Layout.setHorizontalGroup(
            viewMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMenuPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(viewMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayMenu1)
                    .addGroup(viewMenuPanel1Layout.createSequentialGroup()
                        .addComponent(foodBut1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(dessBut1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(drinksBut1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(miscBut1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewMenuPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        viewMenuPanel1Layout.setVerticalGroup(
            viewMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMenuPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(viewMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodBut1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dessBut1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinksBut1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miscBut1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        orderSplit1.setRightComponent(viewMenuPanel1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ORDER #XXX");

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 0));
        jButton2.setText("BACK");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 0));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toGoLayout = new javax.swing.GroupLayout(toGo);
        toGo.setLayout(toGoLayout);
        toGoLayout.setHorizontalGroup(
            toGoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderSplit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(toGoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        toGoLayout.setVerticalGroup(
            toGoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toGoLayout.createSequentialGroup()
                .addGroup(toGoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(toGoLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(orderSplit1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        holderPane.add(toGo, "addOrdPane");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(holderPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(holderPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toGoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toGoButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toGoButActionPerformed

    private void addTabButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTabButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTabButActionPerformed

    private void bookingButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingButActionPerformed

    private void adminButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButActionPerformed

    private void menuButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)holderPane.getLayout();
        card.show(holderPane, "menuPane");
    }//GEN-LAST:event_menuButActionPerformed

    private void foodButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodButActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void tab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tab1ActionPerformed

    private void tab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tab2ActionPerformed

    private void foodBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodBut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodBut1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Basic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RecName;
    private javax.swing.JLabel RecName1;
    private javax.swing.JLabel RecOrdNum;
    private javax.swing.JLabel RecOrdNum1;
    private javax.swing.JLabel RecTableNum;
    private javax.swing.JLabel RecTableNum1;
    private javax.swing.JPanel addOrderPane;
    private javax.swing.JButton addTabBut;
    private javax.swing.JButton adminBut;
    private javax.swing.JLayeredPane baseDisplay;
    private javax.swing.JButton bookingBut;
    private javax.swing.JPanel bookingPane;
    private javax.swing.JButton clockIOBut;
    private javax.swing.JButton dessBut;
    private javax.swing.JButton dessBut1;
    private javax.swing.JLayeredPane displayMenu;
    private javax.swing.JLayeredPane displayMenu1;
    private javax.swing.JButton drinksBut;
    private javax.swing.JButton drinksBut1;
    private javax.swing.JLabel eachTxt;
    private javax.swing.JLabel eachTxt1;
    private javax.swing.JLabel eachTxt2;
    private javax.swing.JLabel eachTxt3;
    private javax.swing.JButton foodBut;
    private javax.swing.JButton foodBut1;
    private javax.swing.JPanel holderPane;
    private javax.swing.JPanel homePane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jTime;
    private javax.swing.JButton menuBut;
    private javax.swing.JButton miscBut;
    private javax.swing.JButton miscBut1;
    private javax.swing.JLabel nameTxt;
    private javax.swing.JLabel nameTxt1;
    private javax.swing.JSplitPane orderSplit;
    private javax.swing.JSplitPane orderSplit1;
    private javax.swing.JPanel payBill;
    private javax.swing.JButton payBillBut;
    private javax.swing.JLabel qtyTxt;
    private javax.swing.JLabel qtyTxt1;
    private javax.swing.JScrollPane recAdds;
    private javax.swing.JScrollPane recAdds1;
    private javax.swing.JPanel recInfoTxt;
    private javax.swing.JPanel recInfoTxt1;
    private javax.swing.JLayeredPane recPanel;
    private javax.swing.JLayeredPane recPanel1;
    private javax.swing.JPanel recTabInfoTxt;
    private javax.swing.JPanel recTabInfoTxt1;
    private javax.swing.JButton tab1;
    private javax.swing.JButton tab10;
    private javax.swing.JButton tab11;
    private javax.swing.JButton tab2;
    private javax.swing.JButton tab3;
    private javax.swing.JButton tab4;
    private javax.swing.JButton tab5;
    private javax.swing.JButton tab6;
    private javax.swing.JButton tab8;
    private javax.swing.JButton tab9;
    private javax.swing.JPanel toGo;
    private javax.swing.JButton toGoBut;
    private javax.swing.JLayeredPane viewMenuPanel;
    private javax.swing.JLayeredPane viewMenuPanel1;
    // End of variables declaration//GEN-END:variables
}
